title       : Consciense Docs
description : Consciense Docs website!

logo        : "/assets/images/logo-full-sm.png"
favicon_ico : "/assets/images/favicon.ico"

color_scheme: dark # dark or light

theme       : just-the-docs # do not change
url         : https://just-the-docs.github.io

aux_links_new_tab: true
aux_links:
  Sciense.org: https://sciense.org